[tool.poetry]
name = "wikiracer-py"
version = "0.1.0"
description = ""
authors = ["Ben Sandler <ben.sandler@opendoor.com>"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
